[policy]
name = "include_order"
order_header = ["standard", "third_party", "project", "local"]
order_source = ["main", "standard", "third_party", "project", "local"]
main_header_extensions = [".hpp", ".h", ".hh", ".hxx"]

[policy.group_titles]
main = "Main header"
standard = "Standard Cpp Libraries"
third_party = "Third-party headers"
project = "Project headers"
local = "User Defined Headers"

[policy.third_party_labels]

[policy.convergence]
domain = "includes.structure"
priority = 900
