[policy]
name = "include_guards"
enabled = false
type = "python"
touch_contract = "preprocessor_only" # any | code_only | preprocessor_only | whitespace_only

# options: pragma_once | include_guard | both
mode = "pragma_once"
header_extensions = [".h", ".hpp", ".hh", ".hxx"]
