[policy]
name = "naming_conventions"

[policy.standards.mj]
local_prefix = "_"
member_prefix = "m_"
global_prefix = "g_"
static_prefix = "s_"
const_prefix = "c_"
atomic_prefix = "a_"
pointer_prefix = "p_"
shared_ptr_prefix = "sp_"
unique_ptr_prefix = "up_"
weak_ptr_prefix = "wp_"
constexpr_prefix_upper = "C_"
static_prefix_upper = "S_"
function_case = "snake"
type_case = "camel"
namespace_case = "camel"
macro_case = "upper_snake"
constexpr_case = "upper_snake"

[policy.standards.google]
local_prefix = ""
member_prefix = ""
global_prefix = "g_"
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""
function_case = "camel"
type_case = "camel"
namespace_case = "lower"
macro_case = "upper_snake"
constexpr_case = "camel"

[policy.standards.llvm]
local_prefix = ""
member_prefix = "m"
global_prefix = ""
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""
function_case = "camel"
type_case = "camel"
namespace_case = "lower"
macro_case = "upper_snake"
constexpr_case = "camel"

[policy.standards.qt]
local_prefix = ""
member_prefix = "m_"
global_prefix = ""
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""
function_case = "camel"
type_case = "camel"
namespace_case = "camel"
macro_case = "upper_snake"
constexpr_case = "camel"
