[policy]
name = "naming_conventions"

[policy.standards.mj]
local_prefix = "_"
member_prefix = "m_"
global_prefix = "g_"
static_prefix = "s_"
const_prefix = "c_"
atomic_prefix = "a_"
pointer_prefix = "p_"
shared_ptr_prefix = "sp_"
unique_ptr_prefix = "up_"
weak_ptr_prefix = "wp_"
function_prefix = "f_"
reference_prefix = "r_"
volatile_prefix = "v_"
enum_var_prefix = "e_"
struct_var_prefix = "t_"
constexpr_prefix_upper = "C_"
static_prefix_upper = "S_"

[policy.standards.google]
local_prefix = ""
member_prefix = ""
global_prefix = "g_"
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
function_prefix = ""
reference_prefix = ""
volatile_prefix = ""
enum_var_prefix = ""
struct_var_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""

[policy.standards.llvm]
local_prefix = ""
member_prefix = "m"
global_prefix = ""
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
function_prefix = ""
reference_prefix = ""
volatile_prefix = ""
enum_var_prefix = ""
struct_var_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""

[policy.standards.qt]
local_prefix = ""
member_prefix = "m_"
global_prefix = ""
static_prefix = ""
const_prefix = ""
atomic_prefix = ""
pointer_prefix = ""
shared_ptr_prefix = ""
unique_ptr_prefix = ""
weak_ptr_prefix = ""
function_prefix = ""
reference_prefix = ""
volatile_prefix = ""
enum_var_prefix = ""
struct_var_prefix = ""
constexpr_prefix_upper = "k"
static_prefix_upper = ""
